name             'fileutils'
maintainer       'Nordstrom, Inc.'
maintainer_email 'itunixadminall@nordstrom.com'
license          'All rights reserved'
description      'Recursively modify owner, group, mode settings or delete files and directories'
version          '1.1.2'
source_url       'https://github.com/nordstrom/fileutils-cookbook.git'
issues_url       'https://github.com/nordstrom/fileutils-cookbook.git'
supports         'rhel'
supports         'solaris2'
