name             'fileutils'
maintainer       'Nordstrom, Inc.'
maintainer_email 'CHANGE_ME_TO_SOMETHING_APPROPRIATE@nordstrom.com'
license          'All rights reserved'
description      'Installs/Configures fileutils'
version          '0.0.0'
source_url       'https://git.nordstrom.net/projects/ITS/repos/fileutils'
issues_url       'https://jira.nordstrom.net/browse/UIS'
