name             'fileutils'
chef_version     '>= 12.5'
maintainer       'Nordstrom, Inc.'
maintainer_email 'itunixadminall@nordstrom.com'
license          'Apache-2.0'
description      'Recursively modify (chown, chmod)  owner, group, mode settings or delete files and directories'
version          '1.2.0'
source_url       'https://github.com/nordstrom/fileutils-cookbook'
issues_url       'https://github.com/nordstrom/fileutils-cookbook/issues'
supports         'redhat'
supports         'solaris2'
